CLS_AMAZON = 0x00
CLS_SORCERESS = 0x01
CLS_NECROMANCER = 0x02
CLS_PALADIN = 0x03
CLS_BARBARIAN = 0x04
CLS_DRUID = 0x05
CLS_ASSASSIN = 0x06

CLASS_NAMES = {
    CLS_AMAZON: 'Amazon',
    CLS_SORCERESS: 'Sorceress',
    CLS_NECROMANCER: 'Necromancer',
    CLS_PALADIN: 'Paladin',
    CLS_BARBARIAN: 'Barbarian',
    CLS_DRUID: 'Druid',
    CLS_ASSASSIN: 'Assassin',
}
